// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package aca.proto;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_ServerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_ServerStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_UserLoggedIn_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_UserLoggedIn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_UserLoggedOut_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_UserLoggedOut_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_UserSentGlobalMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_UserSentGlobalMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_UserSentPrivateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_UserSentPrivateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aca_proto_ChatMsg_Failure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aca_proto_ChatMsg_Failure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\taca.proto\"\256\005\n\007ChatMsg\022" +
      "\014\n\004time\030\001 \002(\003\022\020\n\010metadata\030* \001(\t\0227\n\014serve" +
      "rStatus\030\002 \001(\0132\037.aca.proto.ChatMsg.Server" +
      "StatusH\000\0227\n\014userLoggedIn\030\003 \001(\0132\037.aca.pro" +
      "to.ChatMsg.UserLoggedInH\000\0229\n\ruserLoggedO" +
      "ut\030\004 \001(\0132 .aca.proto.ChatMsg.UserLoggedO" +
      "utH\000\022I\n\025userSentGlobalMessage\030\005 \001(\0132(.ac" +
      "a.proto.ChatMsg.UserSentGlobalMessageH\000\022" +
      "K\n\026userSentPrivateMessage\030\007 \001(\0132).aca.pr" +
      "oto.ChatMsg.UserSentPrivateMessageH\000\022-\n\007" +
      "failure\030\006 \001(\0132\032.aca.proto.ChatMsg.Failur" +
      "eH\000\032\036\n\014ServerStatus\022\016\n\006status\030\001 \002(\t\032 \n\014U" +
      "serLoggedIn\022\020\n\010userName\030\001 \002(\t\032!\n\rUserLog" +
      "gedOut\022\020\n\010userName\030\001 \002(\t\032:\n\025UserSentGlob" +
      "alMessage\022\020\n\010userName\030\002 \002(\t\022\017\n\007message\030\001" +
      " \002(\t\032K\n\026UserSentPrivateMessage\022\016\n\006sender" +
      "\030\002 \002(\t\022\020\n\010receiver\030\003 \003(\t\022\017\n\007message\030\001 \002(" +
      "\t\032\032\n\007Failure\022\017\n\007message\030\001 \001(\tB\005\n\003msgB\002P\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_aca_proto_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aca_proto_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_descriptor,
        new java.lang.String[] { "Time", "Metadata", "ServerStatus", "UserLoggedIn", "UserLoggedOut", "UserSentGlobalMessage", "UserSentPrivateMessage", "Failure", "Msg", });
    internal_static_aca_proto_ChatMsg_ServerStatus_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(0);
    internal_static_aca_proto_ChatMsg_ServerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_ServerStatus_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_aca_proto_ChatMsg_UserLoggedIn_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(1);
    internal_static_aca_proto_ChatMsg_UserLoggedIn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_UserLoggedIn_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_aca_proto_ChatMsg_UserLoggedOut_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(2);
    internal_static_aca_proto_ChatMsg_UserLoggedOut_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_UserLoggedOut_descriptor,
        new java.lang.String[] { "UserName", });
    internal_static_aca_proto_ChatMsg_UserSentGlobalMessage_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(3);
    internal_static_aca_proto_ChatMsg_UserSentGlobalMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_UserSentGlobalMessage_descriptor,
        new java.lang.String[] { "UserName", "Message", });
    internal_static_aca_proto_ChatMsg_UserSentPrivateMessage_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(4);
    internal_static_aca_proto_ChatMsg_UserSentPrivateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_UserSentPrivateMessage_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Message", });
    internal_static_aca_proto_ChatMsg_Failure_descriptor =
      internal_static_aca_proto_ChatMsg_descriptor.getNestedTypes().get(5);
    internal_static_aca_proto_ChatMsg_Failure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aca_proto_ChatMsg_Failure_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
